sylius_resource:
    resources:
        vsapp.games:
            driver: doctrine/orm
            classes:
                model: App\Entity\Game
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\GameController
                form: App\Form\GameForm
        vsapp.game_categories:
            driver: doctrine/orm
            classes:
                model: App\Entity\GameCategory
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\GameCategoryController
                form: App\Form\GameCategoryForm
        vsapp.game_rooms:
            driver: doctrine/orm
            classes:
                model: App\Entity\GameRoom
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\GameRoomController
                form: App\Form\GameRoomForm
        vsapp.game_players:
            driver: doctrine/orm
            classes:
                model: App\Entity\GamePlayer
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                controller: App\Controller\AdminPanel\GamePlayerController
                form: App\Form\GamePlayerForm
        vsapp.mercure_connections:
            driver: doctrine/orm
            classes:
                model: App\Entity\MercureConnection
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
