services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\Chess\:
        resource: '../../../../src/Controller/Chess'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\Chess\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\Chess\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
