monolog:
    channels: [event,doctrine,console,websocket]
    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!websocket"]
        websocket:
            type: stream
            path: '%kernel.logs_dir%/websocket.log' 
            level: info
            channels: ["websocket"]