framework:
    assets:
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/contract-bridge/build/default/manifest.json'
            card-game:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/card-game/manifest.json'
webpack_encore:
    output_path: '%kernel.project_dir%/public/contract-bridge/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/contract-bridge/build/default'
        CardGameTheme: '%kernel.project_dir%/public/shared_assets/build/card-game'
