parameters:
    app_websocket_chat_url: '%env(WEBSOCKET_CHAT_URL)%'
    app_websocket_game_url: '%env(WEBSOCKET_GAME_URL)%'
    app_game_for_gold: '%env(bool:GAME_FOR_GOLD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ##############################################################
    # Websocket Servers
    ##############################################################
    app_websocket_chat_command:
        class: App\Component\Websocket\WebsocketChatServer
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
            - '@logger'
            - {
                sslCertificateKey: '%env(SSL_CERTIFICATE_KEY)%',
                sslCertificateCert: '%env(SSL_CERTIFICATE_CERT)%'
            }
        tags:
            - 'console.command'
    
    app_websocket_game_command:
        class: App\Component\Websocket\WebsocketGameServer
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
            - '@serializer'
            - '@logger'
            - {
                sslCertificateKey: '%env(SSL_CERTIFICATE_KEY)%',
                sslCertificateCert: '%env(SSL_CERTIFICATE_CERT)%'
            }
        tags:
            - 'console.command'
            
    app_websocket_client_factory:
        class: App\Component\Websocket\WebsocketClientFactory
        public: true
        arguments:
            - '@serializer'
            - '%app_websocket_chat_url%'
            - '%app_websocket_game_url%'
            
    app_game_service:
        class: App\Component\GameService
        public: true
        arguments:
            - '@logger'
            - '@serializer'
            - '@vs_users.repository.users'
            - '@vs_users.security_bridge'
            - '@app_game_manager_factory'
        tags:
            - { name: app.game_service, priority: -2000 }
            #- { name: kernel.event_listener, event: kernel.response, priority: -2000 }
            
    app_game_manager_factory:
        class: App\Component\Manager\GameManagerFactory
        arguments:
            - '@logger'
            - '@serializer'
            - '@liip_imagine.cache.manager'
            - '@event_dispatcher'
            - '@doctrine'
            - '@app_backgammon_game_factory'
            - '@vsapp.repository.games'
            - '@vsapp.repository.game_sessions'
            - '@vsapp.factory.game_sessions'
            - '@vsapp.repository.game_players'
            - '@vsapp.repository.temp_players'
            - '@vsapp.factory.temp_players'
            - '%app_game_for_gold%'
    
    ##############################################################
    # Game Rules
    ##############################################################
    app_backgammon_game_factory:
        class: App\Component\Rules\Backgammon\GameFactory
        arguments:
            - '@logger'
    
    
    ##############################################################
    # Game Controllers
    ##############################################################
    App\Controller\Games\SvaraController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
    
    App\Controller\Games\BridgeBeloteController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ContractBridgeController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ChessController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\BackgammonController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
