services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\Games\SvaraController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
    
    App\Controller\Games\BridgeBeloteController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ContractBridgeController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ChessController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\BackgammonController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
