parameters:
    app_zmqsocket_url: '%env(ZMQSOCKET_URL)%'
    app_websocket_publisher_url: '%env(WEBSOCKET_PUBLISHER_URL)%'
    app_websocket_chat_url: '%env(WEBSOCKET_CHAT_URL)%'
    app_websocket_game_url: '%env(WEBSOCKET_GAME_URL)%'
    app_game_for_gold: '%env(bool:GAME_FOR_GOLD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    app_websocket_chat_command:
        class: App\Component\Websocket\WebsocketChatCommand
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
        tags:
            - 'console.command'
    
    app_websocket_game_command:
        class: App\Component\Websocket\WebsocketGameCommand
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
        tags:
            - 'console.command'
            
    app_websocket_event_subscriber:
        class: App\EventListener\WebsocketEventSubscriber
        tags: [kernel.event_subscriber]
    
#     App\EventListener\GameRequestListener:
#         arguments:
#             - '@app_websocket_client_factory'
#             - '@app_game_service'
#         tags:
#             - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            
    App\EventListener\GameEndedListener:
        arguments:
            - '@doctrine'
            - '@vsapp.repository.game_sessions'
        tags:
           -  { name: kernel.event_listener, event: app.game_ended, method: onGameEnded }
            
    app_websocket_client_factory:
        class: App\Component\Websocket\WebsocketClientFactory
        public: true
        arguments:
            - '@serializer'
            - '%app_websocket_chat_url%'
            - '%app_websocket_game_url%'
            - '%app_websocket_publisher_url%'
            - '%app_zmqsocket_url%'
            
    app_game_service:
        class: App\Component\GameService
        public: true
        arguments:
            - '@logger'
            - '@serializer'
            - '@vs_users.repository.users'
            - '@vs_users.security_bridge'
            - '@app_game_manager_factory'
            
    app_game_manager_factory:
        class: App\Component\Manager\GameManagerFactory
        arguments:
            - '@logger'
            - '@serializer'
            - '@event_dispatcher'
            - '@doctrine'
            - '@vsapp.repository.games'
            - '@vsapp.repository.game_sessions'
            - '@vsapp.factory.game_sessions'
            - '@vsapp.repository.game_players'
            - '@vsapp.repository.temp_players'
            - '@vsapp.factory.temp_players'
            - '%app_game_for_gold%'
    
    ##############################################################
    # Game Controllers
    ##############################################################
    App\Controller\Games\SvaraController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
    
    App\Controller\Games\BridgeBeloteController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ContractBridgeController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ChessController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\BackgammonController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
