parameters:
    app_websocket_chat_url: '%env(WEBSOCKET_CHAT_URL)%'
    app_websocket_game_url: '%env(WEBSOCKET_GAME_URL)%'
    
    ###########################################################
    # If need to have Exception Trace In Log
    # Set this ENV Variable in .env File With Value True
    # ----------------------------------------------------
    # For Example: WEBSOCKET_EXCEPTION_TRACE=true
    ###########################################################
    env(WEBSOCKET_EXCEPTION_TRACE): 'false'
    
    ########################################################################################################################
    # If need to have Logs for Any Contexts
    # Set this ENV Variable in .env File With Array of Desired Log Contexts
    # ----------------------------------------------------
    # For Example: WEBSOCKET_GAME_LOGGER_CONTEXTS='["GameServer","GameService","GameManager","GamePlay","GenerateMoves","FirstThrowState","SwitchPlayer","EngineGenerateMoves"]'
    #######################################################################################################################
    env(WEBSOCKET_GAME_LOGGER_CONTEXTS): '[]'

    app_end_game_on_total_think_time_elapse: '%env(bool:END_GAME_ON_TOTAL_THINK_TIME_ELAPSE)%'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true

    ##############################################################
    # Custom Loggers
    ##############################################################
    app_game_logger:
        class: App\Component\GameLogger
        public: true
        arguments:
            - '@monolog.logger.websocket_game'
            - '%env(APP_ENV)%'
            - '%kernel.project_dir%'
            - '%env(json:WEBSOCKET_GAME_LOGGER_CONTEXTS)%'
    
    ##############################################################
    # Custom Serializer Normalizers
    ##############################################################
    App\Component\Serializer\Normalizer\MoveDtoDenormalizer:
        tags:
            # register the normalizer with a high priority (called earlier)
            - { name: 'serializer.normalizer', priority: 500 }
    App\Component\Serializer\Normalizer\MovesMadeActionDtoDenormalizer:
        tags:
            # register the normalizer with a high priority (called earlier)
            - { name: 'serializer.normalizer', priority: 500 }
    App\Component\Serializer\Normalizer\BidDtoDenormalizer:
        tags:
            # register the normalizer with a high priority (called earlier)
            - { name: 'serializer.normalizer', priority: 500 }
    App\Component\Serializer\Normalizer\BidMadeActionDtoDenormalizer:
        tags:
            # register the normalizer with a high priority (called earlier)
            - { name: 'serializer.normalizer', priority: 500 }
    
    ##############################################################
    # Websocket Servers
    ##############################################################
    app_websocket_chat_command:
        class: App\Component\Websocket\WebsocketChatServer
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
            - '%env(APP_ENV)%'
            - '@serializer'
            - '@monolog.logger.websocket_chat'
            - {
                sslCertificateKey: '%env(SSL_CERTIFICATE_KEY)%',
                sslCertificateCert: '%env(SSL_CERTIFICATE_CERT)%'
            }
        tags:
            - 'console.command'
    
    app_websocket_game_command:
        class: App\Component\Websocket\WebsocketGameServer
        arguments:
            - '@service_container'
            - '@doctrine'
            - '@validator'
            - '@app_game_service'
            - '@app_game_logger'
            - '@serializer'
            - {
                sslCertificateKey: '%env(SSL_CERTIFICATE_KEY)%',
                sslCertificateCert: '%env(SSL_CERTIFICATE_CERT)%',
                logExceptionTrace: '%env(bool:WEBSOCKET_EXCEPTION_TRACE)%'
            }
        tags:
            - 'console.command'
            
    app_websocket_client_factory:
        class: App\Component\Websocket\WebsocketClientFactory
        public: true
        arguments:
            - '@serializer'
            - '%app_websocket_chat_url%'
            - '%app_websocket_game_url%'
            
    app_game_service:
        class: App\Component\GameService
        public: true
        shared: true
        arguments:
            - '@app_game_logger'
            - '@serializer'
            - '@vs_users.repository.users'
            - '@vs_users.security_bridge'
            - '@app_game_manager_factory'
        tags:
            - { name: app.game_service, priority: -2000 }
            #- { name: kernel.event_listener, event: kernel.response, priority: -2000 }
            
    app_game_manager_factory:
        class: App\Component\Manager\GameManagerFactory
        arguments:
            - '@app_game_logger'
            - '@serializer'
            - '@liip_imagine.cache.manager'
            - '@event_dispatcher'
            - '@doctrine'
            - '@app_game_factory'
            - '@vsapp.repository.games'
            - '@vsapp.repository.game_sessions'
            - '@vsapp.factory.game_sessions'
            - '@vsapp.repository.game_players'
            - '@vsapp.factory.temp_players'
            - '%app_end_game_on_total_think_time_elapse%'
    
    app_games_event_listener:
        class: App\EventListener\GamesEventListener
        arguments:
            - '@app_game_logger'
            - '@app_game_service'
    
    ##############################################################
    # Game Rules
    ##############################################################
    app_game_factory:
        class: App\Component\Rules\GameFactory
        arguments:
            - '@app_game_logger'
    
    ##############################################################
    # Game Controllers
    ##############################################################
    App\Controller\GamePlatform\InviteController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_users.security_bridge'
            - '@app_game_service'
    
    App\Controller\Games\SvaraController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
    
    App\Controller\Games\BridgeBeloteController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ContractBridgeController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\ChessController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
            
    App\Controller\Games\BackgammonController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
            - '@vsapp.repository.games'
            - '@http_client'
