services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Controller\AdminPanel\DefaultController:
        tags: ['controller.service_arguments']

    App\Controller\Application\DebugController:
        arguments:
            - '@service_container'
        tags: ['controller.service_arguments']
        
    App\Controller\AdminPanel\GameExtController:
        tags: ['controller.service_arguments']
        arguments:
            - '@vs_application.repository.taxonomy'
            - '@vsapp.repository.games'
