parameters:
    vs_application.filemanager_shared_media_gaufrette.app_pictures: "%kernel.project_dir%/public/shared_media/gaufrette/app_pictures"
    vs_application.gaufrette.app_pictures.filesystem: vs_application_app_pictures

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    vs_application.app_pictures_uploader.filesystem:
        class: Gaufrette\Filesystem
        arguments: ['%vs_application.gaufrette.app_pictures.filesystem%']
        factory: ['@knp_gaufrette.filesystem_map', 'get']
        
    vs_application.app_pictures_uploader:
        class: App\Component\Uploader\GamePictureUploader
        arguments:
            - '@vs_application.app_pictures_uploader.filesystem'
            - '@vs_cms.file_path_generator'


