vsapp_game_platform_applications:
    resource: |
        alias: vsapp.game_platform_application
        except: ['show']
        path: /game-platform-applications
        templates: "Pages/GamePlatformApplications"
    type: sylius.resource
    
vsapp_game_platform_settings:
    resource: |
        alias: vsapp.game_platform_settings
        except: ['show']
        path: /game-platform-settings
        templates: "Pages/GamePlatformSettings"
    type: sylius.resource

vsapp_games:
    resource: |
        alias: vsapp.games
        except: ['show']
        path: /games
        templates: "Pages/Games"
    type: sylius.resource

vsapp_game_categories:
    resource: |
        alias: vsapp.game_categories
        except: ['show']
        path: /game-categories
        templates: "Pages/GameCategories"
    type: sylius.resource
    
vsapp_game_players:
    resource: |
        alias: vsapp.game_players
        except: ['show']
        path: /game-players
        templates: "Pages/GamePlayers"
    type: sylius.resource
