

vsapp_games:
    resource: |
        alias: vsapp.games
        #except: ['show']
        path: /games
        templates: "admin-panel/Pages/Games"
    type: sylius.resource


vsapp_game_categories:
    resource: |
        alias: vsapp.game_categories
        #except: ['show']
        path: /game-categories
        templates: "admin-panel/Pages/GameCategories"
    type: sylius.resource
