bridge_belote:
    path: /game/bridge-belote
    controller: App\Controller\BridgeBelote\DefaultController::index
    
contract_bridge:
    path: /game/contract-bridge
    controller: App\Controller\ContractBridge\DefaultController::index

chess:
    path: /game/chess
    controller: App\Controller\Chess\DefaultController::index
   
backgammon:
    path: /game/backgammon
    controller: App\Controller\Backgammon\DefaultController::index
