app_games:
    path: /games
    controller: App\Controller\GamePlatformNew\GamesController::index

bridge_belote:
    path: /games/bridge-belote
    controller: App\Controller\BridgeBelote\DefaultController::index
    
contract_bridge:
    path: /games/contract-bridge
    controller: App\Controller\ContractBridge\DefaultController::index

chess:
    path: /games/chess
    controller: App\Controller\Chess\DefaultController::index
   
backgammon:
    path: /games/backgammon
    controller: App\Controller\Backgammon\DefaultController::index
