debug_sse:
    path: /games/debug-games
    controller: App\Controller\GamePlatform\DebugController::index

debug_sse_add_backgammon_ai_player:
    path: /games/debug-games/{gameSlug}/add-ai-player
    controller: App\Controller\GamePlatform\DebugController::addBackgammonAiPlayer
