app_about_application:
    path: /about-application
    controller: App\Controller\GamePlatform\PagesController::aboutApplication

app_games:
    path: /games
    controller: App\Controller\GamePlatform\GamesController::index

bridge_belote:
    path: /games/bridge-belote
    controller: App\Controller\BridgeBelote\DefaultController::index
    
contract_bridge:
    path: /games/contract-bridge
    controller: App\Controller\ContractBridge\DefaultController::index

chess:
    path: /games/chess
    controller: App\Controller\Chess\DefaultController::index
   
backgammon:
    path: /games/backgammon
    controller: App\Controller\Backgammon\DefaultController::index
    
app_ajax_create_player:
    path: /ajax/create-player-for-user/{userId}
    controller: App\Controller\GamePlatform\AjaxController::createPlayerForUser
