app_about_application:
    path: /about-application
    controller: App\Controller\GamePlatform\PagesController::aboutApplication

app_games:
    path: /games
    controller: App\Controller\GamePlatform\GamesController::index

app_ajax_create_player:
    path: /ajax/create-player-for-user/{userId}
    controller: App\Controller\GamePlatform\AjaxController::createPlayerForUser

app_create_invite:
    path: /ajax/invite/create/{gameCode}-{gameVariant}
    controller: App\Controller\GamePlatform\InviteController::createInviteAction

###################################################################################
# Social Media Login
###################################################################################
connect_facebook_start:
    path: /connect/facebook
    controller: App\Controller\GamePlatform\SocialNetworks\FacebookController::connectAction

connect_facebook_check:
    path: /connect/facebook/check
    controller: App\Controller\GamePlatform\SocialNetworks\FacebookController::connectCheckAction
    
connect_google_start:
    path: /connect/google
    controller: App\Controller\GamePlatform\SocialNetworks\GoogleController::connectAction

connect_google_check:
    path: /connect/google/check
    controller: App\Controller\GamePlatform\SocialNetworks\GoogleController::connectCheckAction
    
qr_code_ga:
    path: /members/qr/ga
    controller: App\Controller\GamePlatform\SocialNetworks\QrCodeController::displayGoogleAuthenticatorQrCode
    
qr_code_totp:
    path: /members/qr/totp
    controller: App\Controller\GamePlatform\SocialNetworks\QrCodeController::displayTotpQrCode

###################################################################################
# Games
###################################################################################
test_card_game:
    path: /games/test-card-game
    controller: App\Controller\Games\TestCardGameController::index
svara:
    path: /games/svara
    controller: App\Controller\Games\SvaraController::index

bridge_belote:
    path: /games/bridge-belote
    controller: App\Controller\Games\BridgeBeloteController::index
    
contract_bridge:
    path: /games/contract-bridge
    controller: App\Controller\Games\ContractBridgeController::index

chess:
    path: /games/chess
    controller: App\Controller\Games\ChessController::index
   
backgammon:
    path: /games/backgammon
    controller: App\Controller\Games\BackgammonController::index
