app_about_application:
    path: /about-application
    controller: App\Controller\GamePlatform\PagesController::aboutApplication

app_games:
    path: /games
    controller: App\Controller\GamePlatform\GamesController::index

app_ajax_create_player:
    path: /ajax/create-player-for-user/{userId}
    controller: App\Controller\GamePlatform\AjaxController::createPlayerForUser

###################################################################################
# Games
###################################################################################
bridge_belote:
    path: /games/bridge-belote
    controller: App\Controller\Games\BridgeBeloteController::index
    
contract_bridge:
    path: /games/contract-bridge
    controller: App\Controller\Games\ContractBridgeController::index

chess:
    path: /games/chess
    controller: App\Controller\Games\ChessController::index
   
backgammon:
    path: /games/backgammon
    controller: App\Controller\Games\BackgammonController::index
