app_pricing_plans:
    path: /pricing-plans
    controller: App\Controller\GamePlatform\PricingPlansController::index

app_pricing_plans_select:
    path: /pricing-plans/select/{pricingPlanId}
    controller: App\Controller\GamePlatform\PricingPlansController::selectPricingPlan

vs_api_test_mercure_index:
    path: /test-mercure
    controller: App\Controller\Application\TestMercureController::index

vs_api_test_mercure_publish:
    path: /test-mercure/publish
    controller: App\Controller\Application\TestMercureController::publish
    
vs_api_test_websocket_index:
    path: /test-websocket
    controller: App\Controller\Application\TestWebSocketController::index

vs_api_test_websocket_publish:
    path: /test-websocket/publish
    controller: App\Controller\Application\TestWebSocketController::publish
