vs_user_authentication:
    resource: "@VSUsersBundle/Resources/config/routing/authentication.yml"
    prefix:   /
    
vs_user_proffile:
    resource: "@VSUsersBundle/Resources/config/routing/profile.yml"
    prefix:   /

app_login:
    path: /login
    controller: App\Controller\GamePlatform\AuthController::login

app_logout:
    path: /logout
    controller: App\Controller\GamePlatform\AuthController::logout

