monolog:
    channels: [event,doctrine,console,websocket_game,websocket_chat]
    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            channels: ["!websocket"]
        websocket_game:
            type: stream
            path: '%kernel.logs_dir%/websocket_game.log' 
            level: info
            channels: ["websocket_game"]
        websocket_chat:
            type: stream
            path: '%kernel.logs_dir%/websocket_chat.log' 
            level: info
            channels: ["websocket_chat"]
