sylius_resource:
    translation:
        #default_locale: '%locale%'
        locale_provider: sylius.translation_locale_provider.immutable
        #available_locales_provider: sylius.translation.locales_provider
        
    #######################################################################################################################
    # Override default settings
    # -------------------------
    # You Can To Override Many Resource Parameters For All Resources (Including VankoSoft Bundles)
    # View Available Settings in 
    #     \Sylius\Bundle\ResourceBundle\DependencyInjection\Configuration::addSettingsSection(ArrayNodeDefinition $node)
    #######################################################################################################################
    settings:
        paginate: 10
    
    resources:
        vsapp.games:
            driver: doctrine/orm
            classes:
                model: App\Entity\Game
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        vsapp.game_categories:
            driver: doctrine/orm
            classes:
                model: App\Entity\GameCategory
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        vsapp.game_players:
            driver: doctrine/orm
            classes:
                model: App\Entity\GamePlayer
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        vsapp.game_sessions:
            driver: doctrine/orm
            classes:
                model: App\Entity\GamePlay
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        vsapp.mercure_connections:
            driver: doctrine/orm
            classes:
                model: App\Entity\MercureConnection
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        vsapp.temp_players:
            driver: doctrine/orm
            classes:
                model: App\Entity\TempPlayer
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
