sylius_resource:
    #translation:
        #default_locale: '%locale%'
        #locale_provider: sylius.translation.locale_provider.contextual
        #available_locales_provider: sylius.translation.locales_provider
    resources:
        vsapp.games:
            driver: doctrine/orm
            classes:
                model: App\Entity\Game
                interface: Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\AdminPanel\GameController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form: App\Form\GameForm
        vsapp.game_categories:
            driver: doctrine/orm
            classes:
                model: App\Entity\GameCategory
                interface: Sylius\Component\Resource\Model\ResourceInterface
                controller: App\Controller\AdminPanel\GameCategoryController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
                form: App\Form\GameCategoryForm

