twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
    globals:
        app_environment: '%env(APP_ENV)%'
        applicationCompany: '%applicationCompany%'
        applicationTitle: '%applicationTitle%'
        hasTopSearch: '%hasTopSearch%'
        formCreateAccount: '%vs_users.form_create_account%'
        installedBundles: '%kernel.bundles%'
        picturesPath: '%vs_cms.filemanager_shared_media_gaufrette.app_pictures%'
        analyticsMeasurementId: '%env(GOOGLE_MEASUREMENT_ID)%'
        useCkEditor: '%env(resolve:USE_CKEDITOR)%'
        
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    