voryx_thruway:
    realm: 'realm1'
    trusted_url: 'ws://127.0.0.1:8080'
    url: 'ws://127.0.0.1:8080'
    enable_logging: true
    user_provider: null

    #######################################################################
    # See Dependecy Injection Config for Configuring Theese Sections
    #######################################################################
    
    # Locations of the files that need to be scan for the Thruway annotations
    locations:
        files:
            - App\Component\Wamp\WampCallback
    
    # additional worker configuration
    #workers: []
    
    # router configuration
    #router: []
