vs_application_instalator:
    resources:
        instalation_info:
            classes:
                model: App\Entity\Application\InstalationInfo
vs_application:
    project_type: extended_application

    resources:
        application:
            classes:
                model: App\Entity\Application\Application
        settings:
            classes:
                model: App\Entity\Application\Settings
        taxonomy:
            classes:
                model: App\Entity\Application\Taxonomy
        taxon:
            classes:
                model: App\Entity\Application\Taxon
            translation:
                classes:
                    model: App\Entity\Application\TaxonTranslation
        taxon_image:
            classes:
                model: App\Entity\Application\TaxonImage
        translation:
            classes:
                model: App\Entity\Application\Translation
        logentry:
            classes:
                model: App\Entity\Application\LogEntry
        locale:
            classes:
                model: App\Entity\Application\Locale
        cookie_consent_translation:
            classes:
                model: App\Entity\Application\CookieConsentTranslation
        tags_whitelist_context:
            classes:
                model: App\Entity\Application\TagsWhitelistContext
        tags_whitelist_tag:
            classes:
                model: App\Entity\Application\TagsWhitelistTag
        widget_group:
            classes:
                model: App\Entity\Application\WidgetGroup
        widget:
            classes:
                model: App\Entity\Application\Widget
        widgets_registry:
            classes:
                model: App\Entity\Application\WidgetsRegistry

    menu:
        mainApplicationMenu:
            home:
                name: vs_application.menu.site_main.home
                route: app_home
                attributes:
                    iconClass: "bx bxs-dashboard"
                display: false
            games:
                name: vs_application.menu.list_games
                route: vsapp_games_index
                attributes:
                    iconClass: "bx bxs-dashboard"
            user_register:
                name: vs_wgp.form.login.register
                route: vs_users_register_form
                attributes:
                    id: user_register
                    iconClass: "bx bx-user-circle"
            user_login:
                name: vs_wgp.template.menu.login
                route: app_login
                attributes:
                    id: user_login
                    iconClass: "bx bx-user-circle"

        profileMenu:
            profile:
                name: vs_application.menu.my_profile
                route: vs_users_profile_show
                attributes:
                    iconClass: "mdi mdi-account-circle text-muted fs-16 align-middle me-1"
                    
            documentation:
                name: vs_application.menu.documentation
                uri: "javascript:;"
                attributes:
                    iconClass: "mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"
                    
#             about:
#                 name: vs_application.menu.about_application
#                 route: wgp_about_application
#                 attributes:
#                     iconClass: "mdi mdi-lifebuoy text-muted fs-16 align-middle me-1"
                  
            divider_1:
                isDivider: true
            
            logout:
                name: vs_application.menu.logout
                route: app_logout
                attributes:
                    iconClass: "mdi mdi-logout text-muted fs-16 align-middle me-1"
