vs_application_instalator:
    resources:
        instalation_info:
            classes:
                model: App\Entity\Application\InstalationInfo
vs_application:
    project_type: extended_application

    resources:
        application:
            classes:
                model: App\Entity\Application\Application
        settings:
            classes:
                model: App\Entity\Application\Settings
        taxonomy:
            classes:
                model: App\Entity\Application\Taxonomy
        taxon:
            classes:
                model: App\Entity\Application\Taxon
            translation:
                classes:
                    model: App\Entity\Application\TaxonTranslation
        taxon_image:
            classes:
                model: App\Entity\Application\TaxonImage
        translation:
            classes:
                model: App\Entity\Application\Translation
        logentry:
            classes:
                model: App\Entity\Application\LogEntry
        locale:
            classes:
                model: App\Entity\Application\Locale
        cookie_consent_translation:
            classes:
                model: App\Entity\Application\CookieConsentTranslation
        tags_whitelist_context:
            classes:
                model: App\Entity\Application\TagsWhitelistContext
        tags_whitelist_tag:
            classes:
                model: App\Entity\Application\TagsWhitelistTag
        widget_group:
            classes:
                model: App\Entity\Application\WidgetGroup
        widget:
            classes:
                model: App\Entity\Application\Widget
        widgets_registry:
            classes:
                model: App\Entity\Application\WidgetsRegistry

    menu:
        mainApplicationMenu:
            home:
                name: vs_application.menu.site_main.home
                route: app_home
                attributes:
                    iconClass: "bx bxs-dashboard"
                display: false
            
            #########################################
            # Static Pages
            #########################################
            page_contact:
                name: vs_application.menu.contact
                route: vs_application_contact
                display: false
            page_about_application:
                name: vs_application.menu.about_application
                route: app_about_application
                display: false
                
            #########################################
            # Game Pages
            #########################################
            games:
                name: vs_application.menu.list_games
                route: app_games
                attributes:
                    iconClass: "bx bxs-dashboard"
            games_svara:
                name: vs_application.menu.games.svara
                route: svara
                display: false
                attributes:
                    iconClass: "bx bxs-dashboard"
            games_bridge_belote:
                name: vs_application.menu.games.bridge_belote
                route: bridge_belote
                display: false
                attributes:
                    iconClass: "bx bxs-dashboard"
            games_contract_bridge:
                name: vs_application.menu.games.contract_bridge
                route: contract_bridge
                display: false
                attributes:
                    iconClass: "bx bxs-dashboard"
            games_chess:
                name: vs_application.menu.games.chess
                route: chess
                display: false
                attributes:
                    iconClass: "bx bxs-dashboard"
            games_backgammon:
                name: vs_application.menu.games.backgammon
                route: backgammon
                display: false
                attributes:
                    iconClass: "bx bxs-dashboard"
            user_register:
                name: vs_application.menu.site_main.register
                route: vs_users_register_form
                attributes:
                    id: user_register
                    iconClass: "bx bx-user-circle"
            user_login:
                name: vs_application.menu.site_main.login
                route: app_login
                attributes:
                    id: user_login
                    iconClass: "bx bx-user-circle"

        profileMenu:
            profile:
                name: vs_application.menu.my_profile
                route: vs_users_profile_show
                attributes:
                    iconClass: "mdi mdi-account-circle text-muted fs-16 align-middle me-1"
                  
            divider_1:
                isDivider: true
            
            logout:
                name: vs_application.menu.logout
                route: app_logout
                attributes:
                    id: application_logout
                    iconClass: "mdi mdi-logout text-muted fs-16 align-middle me-1"
