framework:
    assets:
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/game-platform/build/default/manifest.json'
#             game-platform-mpa:
#                 json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/game-platform-mpa/manifest.json'
            game-platform-spa:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/game-platform-spa/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/game-platform/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/game-platform/build/default'
#         GamePlatform_MPA: '%kernel.project_dir%/public/shared_assets/build/game-platform-mpa'
        GamePlatform_SPA: '%kernel.project_dir%/public/shared_assets/build/game-platform-spa'
