framework:
    assets:
        packages:
            default:
                json_manifest_path: '%kernel.project_dir%/public/game-platform/build/default/manifest.json'
            game-platform-theme:
                json_manifest_path: '%kernel.project_dir%/public/shared_assets/build/game-platform/manifest.json'

webpack_encore:
    output_path: '%kernel.project_dir%/public/game-platform/build/default'
    builds:
        defaultConfig: '%kernel.project_dir%/public/game-platform/build/default'
        GamePlatformTheme: '%kernel.project_dir%/public/shared_assets/build/game-platform'
