vs_api_get_translations:
    path: /api/get-translations/{locale}
    controller: App\Controller\Api\DefaultController::getTranslationsAction

vs_api_get_verify_signature:
    path: /api/get-verify-signature
    controller: App\Controller\Api\DefaultController::getVerifySignatureAction
    