vs_api_account_signin:
    path: /api/account/signin
    controller: App\Controller\Api\AccountController::signinAction

vs_api_account_toggleintro:
    path: /api/account/toggleIntro
    controller: App\Controller\Api\AccountController::toggleIntroAction
    
vs_api_get_verify_signature:
    path: /api/get-verify-signature
    controller: App\Controller\Api\DefaultController::getVerifySignatureAction

vs_api_game_by_slug:
    path: /api/games-ext/{slug}
    controller: App\Controller\Api\Games\ShowGameBySlugController::index

vs_api_game_play_by_game:
    path: /api/game-sessions/{gameSlug}
    controller: App\Controller\Api\Games\GetGamePlayByGameController::index

vs_api_mercure_game_message:
    path: /api/game-message
    controller: App\Controller\Api\MercureController::index

vs_api_zmq_publish_message:
    path: /api/zmq-message
    controller: App\Controller\Api\ZmqPublishController::publish

vs_api_backgamon_editor_game_string:
    path: /api/backgamon/editor/gamestring
    controller: App\Controller\Api\BackgammonEditorController::gameString

vs_api_create_game_room:
    path: /api/create-game-room/{gameId}
    controller: App\Controller\Api\Games\CreateGameRoomController::createGameRoomAction

vs_api_select_game_room:
    path: /api/select-game-room/{gameId}
    controller: App\Controller\Api\Games\SelectGameRoomController::selectGameRoomAction

vs_api_start_game:
    path: /api/start-game/{gamePlayId}
    controller: App\Controller\Api\Games\StartGameController::startGameAction
    defaults:
        gamePlayId: 0

vs_api_finish_game:
    path: /api/finish-game/{gamePlayId}
    controller: App\Controller\Api\Games\FinishGameController::finishGameAction
