vs_api_get_translations:
    path: /api/get-translations/{locale}
    controller: App\Controller\Api\DefaultController::getTranslationsAction

vs_api_get_verify_signature:
    path: /api/get-verify-signature
    controller: App\Controller\Api\DefaultController::getVerifySignatureAction

vs_api_mercure_game_message:
    path: /api/game-message
    controller: App\Controller\Api\MercureController::index

vs_api_zmq_publish_message:
    path: /api/zmq-message
    controller: App\Controller\Api\ZmqPublishController::publish

vs_api_account_signin:
    path: /api/account/signin
    controller: App\Controller\Api\AccountController::signinAction

vs_api_backgamon_editor_game_string:
    path: /api/backgamon/editor/gamestring
    controller: App\Controller\Api\BackgammonEditorController::gameString
