resources:
    App\Entity\Game:
        operations:
            games_get:
                class: ApiPlatform\Metadata\GetCollection
                method: GET
                uriTemplate: /games
                normalizationContext:
                    groups: ['game:read']
          
        properties:
            id:
                identifier: true
                writeable: false
                required: false
            
