resources:
    App\Entity\GameRoom:
        operations:
            rooms_get:
                class: ApiPlatform\Metadata\GetCollection
                method: GET
                uriTemplate: /rooms
                normalizationContext:
                    groups: ['game-room:read']
                    
            room_get:
                class: ApiPlatform\Metadata\Get
                method: GET
                uriTemplate: /rooms/{id}
                normalizationContext:
                    groups: ['game-room:read']
                    
            room_post:
                class: ApiPlatform\Metadata\Post
                method: POST
                uriTemplate: /rooms/new
                controller: App\Controller\Api\Games\CreateRoomController
                
                read: false # Disable ReadListener
                write: false
                deserialize: false,
                
                normalizationContext:
                    groups: ['game-room:read']
                denormalizationContext:
                    groups: ['game-room:create']
                    
            room_put:
                class: ApiPlatform\Metadata\Put
                method: PUT
                uriTemplate: /rooms/{id}
                controller: App\Controller\Api\Games\EditRoomController
                
                read: false # Disable ReadListener
                write: false
                deserialize: false,
                
                normalizationContext:
                    groups: ['game-room:read']
                denormalizationContext:
                    groups: ['game-room:update']
                    
            room_delete:
                class: ApiPlatform\Metadata\Delete
                method: DELETE
                uriTemplate: /rooms/{id}
                controller: App\Controller\Api\Games\DeleteRoomController
