resources:
    App\Entity\Game:
        operations:
            games_get:
                class: ApiPlatform\Metadata\GetCollection
                method: GET
                uriTemplate: /games
                normalizationContext:
                    groups: ['game:read']
            game_show:
                class: ApiPlatform\Metadata\Get
                method: GET
                uriTemplate: /games/{id}
                controller: App\Controller\Api\Games\ShowGameController
                normalizationContext:
                    groups: ['game:read']
            game_show_by_slug:
                class: ApiPlatform\Metadata\Get
                method: GET
                uriTemplate: /games-ext/{slug}
                requirements:
                    slug: '\w+'
                controller: App\Controller\Api\Games\ShowGameBySlugController
                normalizationContext:
                    groups: ['game:read']
          
        properties:
            id:
                identifier: true
                writeable: false
                required: false
            slug:
                writeable: true
                required: true
            title:
                writeable: true
                required: true
            
