App\Entity\MercureConnection:
    attributes:
        id:
            groups: ['game-room:read']
        enabled:
            groups: ['game-room:read', 'game-room:create', 'game-room:update']
        user:
            groups: ['game-room:read', 'game-room:create', 'game-room:update']