App\Entity\UserManagement\User:
    attributes:
        username:
            groups: ['game:read']
        info:
            groups: ['game:read']

App\Entity\UserManagement\UserInfo:
    attributes:
        firstName:
            groups: ['game:read']
        lastName:
            groups: ['game:read']
            