services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\ContractBridge\:
        resource: '../../../../src/Controller/ContractBridge'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\ContractBridge\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\ContractBridge\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
