services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\BridgeBelote\:
        resource: '../../../../src/Controller/BridgeBelote'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\BridgeBelote\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\BridgeBelote\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
