services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Controller\Backgammon\:
        resource: '../../../../src/Controller/Backgammon'
        tags: ['controller.service_arguments']
        autowire: true
    
    App\Controller\Backgammon\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
    
    App\Controller\Backgammon\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
            - '@twig'
