services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Controller\Api\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_api.api_manager'
            
    App\Controller\Api\Games\ShowGameController:
        arguments:
            - '@doctrine'
            - '@vs_users.security_bridge'
            - '@vsapp.repository.games'
        autowire: false
        tags: ['controller.service_arguments']
        calls:
            - [ setContainer, [ '@service_container' ] ]


