services:
    _defaults:
        autowire: true
        autoconfigure: true
        
    App\Controller\Api\DefaultController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_users.security_bridge'
            - '@vs_api.api_manager'
            
    App\Controller\Api\Games\ShowGameController:
        arguments:
            - '@vsapp.repository.games'
        autowire: false
        tags: ['controller.service_arguments']
        calls:
            - [ setContainer, [ '@service_container' ] ]
            
    App\Controller\Api\Games\ShowGameBySlugController:
        arguments:
            - '@vsapp.repository.games'
        autowire: true
        tags: ['controller.service_arguments']
        
    App\Controller\Api\Games\GetPlayersController:
        arguments:
            - '@vsapp.repository.game_players'
        autowire: true
        tags: ['controller.service_arguments']
    
    App\Controller\Api\Games\ShowPlayerByUserController:
        arguments:
            - '@vs_users.repository.users'
        autowire: true
        tags: ['controller.service_arguments']
            
    App\Controller\Api\Games\GetGamePlayController:
        arguments:
            - '@vsapp.repository.game_sessions'
        autowire: true
        tags: ['controller.service_arguments']
        
    App\Controller\Api\Games\StartGameController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vsapp.factory.game_sessions'
            - '@mercure.hub.default'
        
    App\Controller\Api\Games\FinishGameController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vsapp.repository.game_sessions'
            - '@mercure.hub.default'
    
    App\Controller\Api\MercureController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@mercure.hub.default'
    
    App\Controller\Api\AccountController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@doctrine'
            - '@vs_users.repository.users'
            - '@vsapp.factory.game_sessions'
            - '@mercure.hub.default'
