services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    App\Controller\Api\AuthController:
        tags: ['controller.service_arguments']
        autowire: true
        arguments:
            - '@vs_application.context.application'
