parameters:
    app_websocket_chat_url: '%env(WEBSOCKET_CHAT_URL)%'
    app_websocket_game_url: '%env(WEBSOCKET_GAME_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    app_websocket_client_factory:
        class: App\Component\Websocket\WebsocketClientFactory
        arguments:
            - '@serializer'
            - '%app_websocket_chat_url%'
            - '%app_websocket_game_url%'
    
    app_game_manager_factory:
        class: App\Component\Manager\GameManagerFactory
        arguments:
            - '%env(APP_ENV)%'
            - '@monolog.logger.websocket_game'
            - '@serializer'
            - '@liip_imagine.cache.manager'
            - '@event_dispatcher'
            - '@doctrine'
            - '@app_backgammon_game_factory'
            - '@vsapp.repository.games'
            - '@vsapp.repository.game_sessions'
            - '@vsapp.factory.game_sessions'
            - '@vsapp.repository.game_players'
            - '@vsapp.repository.temp_players'
            - '@vsapp.factory.temp_players'
    
    app_game_service:
        class: App\Component\GameService
        public: true
        arguments:
            - '%env(APP_ENV)%'
            - '@monolog.logger.websocket_game'
            - '@serializer'
            - '@vs_users.repository.users'
            - '@vs_users.security_bridge'
            - '@app_game_manager_factory'
    
    ##############################################################
    # Game Rules
    ##############################################################
    app_backgammon_game_factory:
        class: App\Component\Rules\Backgammon\GameFactory
        arguments:
            - '%env(APP_ENV)%'
            - '@monolog.logger.websocket_game'
