parameters:
    app_websocket_chat_url: '%env(WEBSOCKET_CHAT_URL)%'
    app_websocket_game_url: '%env(WEBSOCKET_GAME_URL)%'

    ########################################################################################################################
    # If need to have Logs for Any Contexts
    # Set this ENV Variable in .env File With Array of Desired Log Contexts
    # ----------------------------------------------------
    # For Example: WEBSOCKET_GAME_LOGGER_CONTEXTS='["GameServer","GameService","GameManager","GamePlay","GenerateMoves"]'
    #######################################################################################################################
    env(WEBSOCKET_GAME_LOGGER_CONTEXTS): '[]'
    
    app_end_game_on_total_think_time_elapse: '%env(bool:END_GAME_ON_TOTAL_THINK_TIME_ELAPSE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    app_game_logger:
        class: App\Component\GameLogger
        public: true
        arguments:
            - '@monolog.logger.websocket_game'
            - '%env(APP_ENV)%'
            - '%kernel.project_dir%'
            - '%env(json:WEBSOCKET_GAME_LOGGER_CONTEXTS)%'
    
    app_websocket_client_factory:
        class: App\Component\Websocket\WebsocketClientFactory
        arguments:
            - '@serializer'
            - '%app_websocket_chat_url%'
            - '%app_websocket_game_url%'
    
    app_game_manager_factory:
        class: App\Component\Manager\GameManagerFactory
        arguments:
            - '@app_game_logger'
            - '@serializer'
            - '@liip_imagine.cache.manager'
            - '@event_dispatcher'
            - '@doctrine'
            - '@app_boardgame_factory'
            - '@app_cardgame_factory'
            - '@vsapp.repository.games'
            - '@vsapp.repository.game_sessions'
            - '@vsapp.factory.game_sessions'
            - '@vsapp.repository.game_players'
            - '@vsapp.repository.temp_players'
            - '@vsapp.factory.temp_players'
            - '%app_end_game_on_total_think_time_elapse%'
    
    app_game_service:
        class: App\Component\GameService
        public: true
        arguments:
            - '@app_game_logger'
            - '@serializer'
            - '@vs_users.repository.users'
            - '@vs_users.security_bridge'
            - '@app_game_manager_factory'
    
    ##############################################################
    # Game Rules
    ##############################################################
    app_boardgame_factory:
        class: App\Component\Rules\BoardGame\GameFactory
        arguments:
            - '@app_game_logger'
    
    app_cardgame_factory:
        class: App\Component\Rules\CardGame\GameFactory
        arguments:
            - '@app_game_logger'
