parameters:
    app_zmqsocket_url: '%env(ZMQSOCKET_URL)%'
    app_websocket_publisher_url: '%env(WEBSOCKET_PUBLISHER_URL)%'
    app_websocket_server_url: '%env(WEBSOCKET_SERVER_URL)%'
    app_game_for_gold: '%env(bool:GAME_FOR_GOLD)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    app_websocket_client_factory:
        class: App\Component\Websocket\WebsocketClientFactory
        arguments:
            - '%app_websocket_server_url%'
            - '%app_websocket_publisher_url%'
            - '%app_zmqsocket_url%'
